### ISSUE TITLE
File Scrubber view assumes continuous time

### ISSUE THREAD

**Issue by glenne** [crewtimer/crewtimer-video-review#30]
The waypoint annotations on the File Scrubber sections currently assumes time is continuous time.  That is, the location of the annotations is drawn as a single view and markers located based on a global start and stop time.

If the video recording has gaps for deleted files or pauses in the recording, the location of the indicators will not be correct.

To fix this, each 'segment' must draw it's own markers based only on that particular file.  

To avoid traversing the entire list of time markers every time a new marker is added perhaps one traversal where the markers are placed into bins and then drawn would be a compromise.

**Comment by glenne** [comment]
Currently the length of a file is not known without opening the file and processing the mpeg headers.  When there are gaps due to deleted files, the length of the file prior to the deleted segment is assumed to extend to the start of the next file.

As a result, when clicking in this 'dead space' the mapping to the VideoScrubber is not accurate.  Icons are drawn in the correct location in the video scrubber but are not in the proper position in the File Scrubber due to the extended length with no data.

To fix this would require the application to scan each file to get an accurate length.  One possible solution would be to store this info in the json file that can be associated with each file.  If the json file does not exist, the mp4 file would need to be processed and the json file updated.

**Comment by glenne** [comment]
Another option would be for the recording app to create the initial json file with meta data to assist with this.  This would eliminate the need for scanning and seeking in every file to make the timeline correct.

**Comment by glenne** [comment]
I propose having the recorder add a .json file with contents as shown below.  This will be the same sidecar file used by the video review software for storing settings like where the finish line is located.  The review software will be modified to silently retain any settings in the json file it doesn't understand so additional meta data can be added without it getting erased by settings updates.

```
{
  "file": {
    "startTs": "1722362359500.000000",
    "stopTs": "1722362359600.000000",
    "numFrames": 3600
  }
}
```

The start and stop timestamps are strings representing UTC seconds to whatever resolution is available.  Should tzOffset seconds be included as well?  This would eliminate the need for the timezone setting in the review software since it would be embedded by the recorder.

**Comment by basrijn** [comment]
> The start and stop timestamps are strings representing UTC seconds to whatever resolution is available. Should tzOffset seconds be included as well? This would eliminate the need for the timezone setting in the review software since it would be embedded by the recorder.

I'll update my software to write the timestamp in the proposed format. Will send you a video file and example tonight.
I would not include the timezone in the file, it's nice to leave the user with the flexibility to make that choice (but default to the browsers TZ)
