### ISSUE TITLE
Small hyperzoom timestamp bug

### ISSUE THREAD

**Issue by basrijn** [crewtimer/crewtimer-video-review#33]
Hyperzoom is awesome!

I think I found a small bug, I was trying to check if the little magnifying glass (estimated ts) disappeared when I hit the next full frame. It was not showing, but I was @ 2ms skip and that jumped over my actual timestamps:

- I set to 1 ms resolution
- Checked actual frames (at x.145, x.154, x.163)
- Jump to the frame before .145 (.137)
- Zoom in
- Scroll 1 ms forward. All good,  until I jump from .144 to .145, it shows .137 instead
- Scroll one more forward and I see .145

It only seems to do it on the first full frame, after that it keeps going by 1ms. I don't see the magnifying glass disappear. Does it keep in the interpolated images, or does it show the actual native frame when it hit a point where there is one available?

**Comment by glenne** [comment]
Can you try this on the 1.0.3 release?  I made some fixes in that area.

crewtimer.com/help/downloads

Glenn

**Comment by glenne** [comment]
Fixed in 1.0.3 release
